const contactUs = () => {
  const content = document.querySelector('#container');
  const contactDiv = document.createElement('div');
  contactDiv.classList.add('contact-div');
  const contactContent = document.createElement('div');
  contactContent.classList.add('contact-content');
  const form = document.createElement('form');
  form.classList.add('page-form');
  const userName = document.createElement('input');
  userName.type = 'text';
  userName.placeholder = 'username';
  userName.classList.add('user-name');
  const email = document.createElement('input');
  email.type = 'email';
  email.placeholder = 'username@gmail.com';
  email.classList.add('email');
  const number = document.createElement('input');
  number.type = 'number';
  number.placeholder = '+234....';
  number.classList.add('number');
  const feedBack = document.createElement('input');
  feedBack.type = 'textarea';
  feedBack.placeholder = 'submit your feedback';
  feedBack.classList.add('feedback');
  const submitBtn = document.createElement('button');
  submitBtn.classList.add('submit-btn');
  submitBtn.type = 'submit';
  submitBtn.textContent = 'submit';
  form.append(userName, email, number, feedBack, submitBtn);
  contactDiv.append(form);
  // contactContent.append(contactDiv);
  content.append(contactDiv);
};
export default contactUs;
